// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_qmovXVUH85RFEVZcx9B69EIJvK8cy0',
    appId: '1:1048254137318:web:e3ef4d9907cdd6209b0c27',
    messagingSenderId: '1048254137318',
    projectId: 'raktacare',
    authDomain: 'raktacare.firebaseapp.com',
    storageBucket: 'raktacare.appspot.com',
    measurementId: 'G-JPGZ0TNE97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoGEPw_Z0e2ZMHBnylBwHJ1bNhnB4Qm90',
    appId: '1:1048254137318:android:006d018db632abe59b0c27',
    messagingSenderId: '1048254137318',
    projectId: 'raktacare',
    storageBucket: 'raktacare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszkf5Q-5UMGn6wLbYxOFU-peenj455Do',
    appId: '1:1048254137318:ios:167ae86b584627399b0c27',
    messagingSenderId: '1048254137318',
    projectId: 'raktacare',
    storageBucket: 'raktacare.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszkf5Q-5UMGn6wLbYxOFU-peenj455Do',
    appId: '1:1048254137318:ios:71b4a846ae2e707a9b0c27',
    messagingSenderId: '1048254137318',
    projectId: 'raktacare',
    storageBucket: 'raktacare.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp.RunnerTests',
  );
}
